### PR TITLE
Fixed an error when the compute node's start lsn is in the first block of a wal segment.

### PR DESCRIPTION
**Pull request by Lzjing-1997**
**steps to reproduce:**
  1. cargo neon init
  2. cargo neon start
  3. cargo neon tenant create --set-default
  4. cargo neon endpoint create master
  5. vim .neon/endpoints/master/postgresql.conf    # add  "max_prepared_transactions=10"
  6. cargo neon endpoint start master
  7. psql -U cloud_admin -d postgres -p55432
  8. postgres=# select pg_switch_wal();
  9. cargo neon endpoint stop master
  10. cargo neon endpoint start master
  11. psql -U cloud_admin -d postgres -p55432
  12. postgres=# begin;
  13. postgres=# create table sa(a int);
  14. postgres=# prepare transaction 'gxid1';
  15. postgres=# commit prepared 'gxid1';    -- Error
  
  ERROR:  could not read two-phase state from WAL at 0/20198A8: invalid info bits 0001 in WAL segment 000000010000000000000002, LSN 0/2000000, offset 0
  
If you think this solution works, I'll apply it to other versions.

### CODE REVIEW

**Comment by tristan957** [comment]
Can you add a test in the Neon repo for this?

**Comment by Lzjing-1997** [comment]
> Can you add a test in the Neon repo for this?

In Neon's repo, I don't think there's a good place to add this test case since it's PG's code, do you have any suggestions on where to add the test case?

**Comment by tristan957** [comment]
No problem. Looks like @hlinnaka worked on a similar solution here: https://github.com/neondatabase/postgres/compare/6e9a4ff6249ac02b8175054b7b3f7dfb198be48b...e6203b5b66f8639461301a980e7a2fb1f9f7562f#diff-12d3e48c566898484e306c9662afb37a426c4601a1efa2a09869d25f2659dd02

https://github.com/neondatabase/neon/pull/8914

**Comment by hlinnaka** [comment]
This was fixed in PR https://github.com/neondatabase/neon/pull/8914. Thanks!

**Pull request closed without merging**
