### PR TITLE
Undo disarming VM check warning in vacuumlazy.c

### PR DESCRIPTION
**Pull request by knizhnik**

### CODE REVIEW

**Review by hlinnaka — APPROVED** [review]
typo in the commit message: "diasming"

To finish this, let's:

1. Fix the commit message, rebase, and force-push to the `undo_vm_change` branch
2. Create a PR in the neon-repository, with these two changes:
- remove the corresponding section from `docs/core_changes.md`, and
- bump vendor/postgres to `undo_vm_change` branch.
3. Wait for the CI to run on that PR. Assuming it's all green:
4. Push this PR to the postgres main branch
5. Push the neon-repo PR to neon main branch

**Comment by hlinnaka** [comment]
But let's finish and push https://github.com/neondatabase/postgres/pull/183 first. We cannot bump vendor/postgres before that.

**Comment by stepashka** [comment]
@hlinnaka , #183 was merged recently, does it mean that this one can be merged too?
are the changes you've mentioned earlier still required?

**Comment by knizhnik** [comment]
Repalced by #213 and #214

**Pull request closed without merging**
