### PR TITLE
revert changes on extension permissions

### PR DESCRIPTION
**Pull request by skyzh**
per discussion in the Slack channel and related GitHub issues, we might need to find another approach to solve https://github.com/neondatabase/neon/issues/6236. Reverting things for now and will submit pull requests again.

@hlinnaka do you feel it's better to do this revert or simply reset the current REL_xx_STABLE_neon branch to your git history? The only things that got changed in the past week are our two patches, and given that mine gets reverted, it's probably easier to do a force push so that we have fewer commits when rebasing to the upstream repo next time?

### CODE REVIEW

**Comment by skyzh** [comment]
(and sorry for tagging during the weekend -- feel free to take over / close my pull request if you decide to do a reset next week as I'm away on Monday)

**Comment by hlinnaka** [comment]
>@hlinnaka do you feel it&#39;s better to do this revert or simply reset the current REL_xx_STABLE_neon branch to your git history? The only things that got changed in the past week are our two patches, and given that mine gets reverted, it&#39;s probably easier to do a force push so that we have fewer commits when rebasing to the upstream repo next time?

Either way works for me

**Comment by skyzh** [comment]
@hlinnaka I think it would be a better idea if you could help reset the branches to remove my commits so that the history is clean and saves the trouble for the next rebase. Thanks!

**Comment by skyzh** [comment]
I got force push permission from Vadim and the git history is fixed 🤣

**Pull request closed without merging**
