### PR TITLE
Store speculative token inside heap insert wal record

### PR DESCRIPTION
**Pull request by knizhnik**
refer #2857

### CODE REVIEW

**Comment by knizhnik** [comment]
> This is going to read out-of-bounds for old data (and may therefore trigger SIGSEGV); so I don't think this is acceptable as-is.
SIGSEGV is possible here because xl_heap_insert record is followed by xl_heap_header which is 33 bytes long.

> I also don't think this is 'just fine' now. Maybe we can emit generic xlog records to splice the speculative token into place?

WAL record  header adds quite large overhead. It can lead to up to 2x times increasing of generated WAL size if application is performing upserts of small records, i.e. key-value pairs.

I agree with @hlinnaka that we "have crossed Rubicon" by adding `t_cid` to xl_heap_header. I do not think that it will be added to vanilla Postgres and even it is accepted by community,  it will be available in release not earlier than in two years.
So I do not think that we should try to avoid other changes in WAL format as much as possible.
For me it is ore important to:
1. Reduce overheader and performance penalty
2. Minimize our changes i Postgres core
I believe that the proposed patch is the smallest and safest one. It is smaller than dealing with separate logical records.

**Comment by knizhnik** [comment]
> so please use the thread feature where possible

Sorry, I do not understand how to use "thread feature" in Git hub comments.
I do not see other Reply options in context menu rather than "Quote reply". So please explain me how to reply properly and I will do it.

Concerning our discussion, I consider  your arguments, but still thinking that doubling WAL size because of using of logical records is not acceptable. And intensive upserts of small records is not something very exotic. It is more or less typical use case when your are monitoring some events (like sensor data in IoT). 
Also I do not see some problems with changing WAL format in future (for example using logical WAL record instead of extending xl_heap_insert). Format is also changed in Vanilla Postgres, so we should be ready to handle it.

There is one more problem with logical records: them can be used by application. So doesn't matter which format of logical message you will use for speculative token - there is absolutely no warranty that there will be no conflict with application logical messages.

So IMHO logical records is not an acceptable solution of the problem. The only possible alternative is pinning pages. But the more I am looking at speculative insertion code, the less I want to dig into this kitchen. I you are familiar with this mechanism, I will be pleased if you can clarify some things to me: for example when heap_abort_speculative() is called and why speculative flag is ignored by insert/update but handled by delete.

**Comment by hlinnaka** [comment]
>If we ever want to be compatible with upstream, we must stop adding more incompatible changes in any communication protocols, be they ABI, WAL, or block format.
> 
> While I agree that the ship has sailed for PG14 and PG15, we are trying to get CID into PG16 so that that incompatibility is resolved. Adding more incompatibilities does actively hinder this effort.

Right. The question in this case is whether we could use the same mechanism to deal with speculative insertion tokens that we use to handle command ids. If the mechanism in Postgres v16 can also be used for the speculative insertion token, then we do that, and it doesn't matter much what we do for v14 and v15 now. But if the same mechanism is not applicable, then we need to come up with something else.

> I'm not planning on using logical WAL records (RM_LOGICALMSG_ID), but generic WAL records (RM_GENERIC_ID, transam/generic_xlog.c). It provides an API for extensions to register page modifications in a common format, where you register that "bytes from offset X to offset Y on page Z have been overwritten with these bytes", and that is then logged in an xlog record, and handled as such during redo.
> 
> The size of such record would be 53 bytes (56 when MAXALIGNED): XLHdrSz (24) + XLBlockHdr (4) + RelFileLocator (3*4 + 1) + BlockNo (4) + 2*OffsetNumber (4) + token (4). A simple heap insert takes at least 59B (64 when MAXALIGNED): XLHdrSz (24) + XLBlockHdr (4) RelFileLocator (3*4 + 1) + BlockNo (4) + xlheap_hdr (9) + XLDataSmall (2B) + xlheap_insert (3B). Sure, that's quite a lot of overhead, but I think that's manageable if it is only for speculative insertion. Note that this already requires that the insert is speculative, which usually implies at least one index, which also needs to be logged (adding at least one more block-referencing record of at least 45 bytes). So, sure, it's not great at 50% overhead (heap + index), but it's not that terrible either.

Where would we generate those records?

I think keeping the page pinned is the most promising approach..

**Comment by hlinnaka** [comment]
> > Where would we generate those records?
> > I think keeping the page pinned is the most promising approach..
> 
> That's to not need to pin pages, so that we don't risk leaking pinned pages or otherwise risking reducing the amount of evictable pages of the buffer pool to 0.

Nah, that's not a problem. Buffer pins are tracked by resource owners, and are automatically cleaned up at end of transaction. We hold buffer pins much longer in index and heap scans, for example.

**Comment by hlinnaka** [comment]
https://github.com/neondatabase/postgres/pull/223 fixed this, closing

**Pull request closed without merging**
