### PR TITLE
Revert handling of UNLOGGED tables on compute side v14

### PR DESCRIPTION
**Pull request by arssher**
They will be handled in pageserver, ref https://github.com/neondatabase/neon/pull/3706

### CODE REVIEW

**Review by knizhnik — COMMENTED** [review]
It seems to me that we need to call ResetUnloggedRelations to make this PR work

**Comment by arssher** [comment]
No, see https://neondb.slack.com/archives/C04DGM6SMTM/p1677238033705799?thread_ts=1676890587.096959&cid=C04DGM6SMTM

**Review by hlinnaka — APPROVED** [review]

**Comment by hlinnaka** [comment]
I wonder if we could now revert commit 285cd136cc, too?

**Comment by arssher** [comment]
Let's see...

**Review by knizhnik — APPROVED** [review]

**Comment by arssher** [comment]
> I wonder if we could now revert commit https://github.com/neondatabase/postgres/commit/285cd136cc0628007b1dd416fbaeb7c41d5cb82f, too?

Tried that. Then `check_restored_datadir_content` complains about diffs in several files
```______________________________________________________________________________________ test_pg_regress _______________________________________________________________________________________
Traceback (most recent call last):
  File "/home/ars/neon/neon2/test_runner/regress/test_pg_regress.py", line 72, in test_pg_regress
    check_restored_datadir_content(test_output_dir, env, pg)
  File "/home/ars/neon/neon2/test_runner/fixtures/neon_fixtures.py", line 3310, in check_restored_datadir_content
    assert (mismatch, error) == ([], [])
AssertionError: assert (['base/16384/27042',\n  'base/16384/27043',\n  'base/16384/27047',\n  'base/16384/27047_init'],\n []) == ([], [])
  At index 0 diff: ['base/16384/27042', 'base/16384/27043', 'base/16384/27047', 'base/16384/27047_init'] != []
  Full diff:
    (
  -  [],
  +  ['base/16384/27042',
  +   'base/16384/27043',
  +   'base/16384/27047',
  +   'base/16384/27047_init'],
     [],
    )
```
That's expected for main forks of unlogged tables (they are empty pageserver version and contain data in compute version), but not sure why one init fork is also different.

**Comment by arssher** [comment]
Right now I don't understand why, and it is already a bit late for release, so won't revert it this time.

**Comment by hlinnaka** [comment]
Ok, thanks for testing!

**Pull request merged**
